### PR TITLE
Create Issue template

### PR DESCRIPTION
**Pull request by v-mohithgc**
**Description**: This should help users to raise issues.
image

**Documentation changes required:** (Y/N) <Please mark if documentation changes are required>

**Added unit tests:** (Y/N) <Please mark if unit tests were added or updated according changes>

**Attached related issue:** (Y/N) <Please add link to related issue here>

**Checklist**:
- [ ] Version was bumped - please check that version of the extension, task or library has been bumped.
- [ ] Checked that applied changes work as expected.

### CODE REVIEW

**Review by manolerazvan — APPROVED** [review]

**Review by LeftTwixWand — COMMENTED** [review]
Looks great!

**Pull request merged**
