### PR TITLE
[ArtifactEngine] Update version to 1.0.0

### PR DESCRIPTION
**Pull request by max-zaytsev**
- Introduce `artifact-engine` version "1.0.0"
- Upgrade `handlebars ` to resolve vulnerabilities for dependent pipeline tasks
- Upgrade `azure-pipelines-task-lib` to "^3.1.0" version

### CODE REVIEW

**Comment by max-zaytsev** [comment]
Hi @harshiniks, @narula0781, Could someone please take a look at this PR?

**Review by harshiniks — APPROVED** [review]

**Comment by harshiniks** [comment]
chandrasekharmudili@github.com is the person you can contact on merging and releasing.

**Comment by chandrasekharmudili** [comment]
Published latest version to https://www.npmjs.com/package/artifact-engine.

**Comment by max-zaytsev** [comment]
@chandrasekharmudili, @harshiniks Thanks!

**Pull request merged**
