### PR TITLE
azure-pipelines-extensions root: Vulnerability fixes 

### PR DESCRIPTION
**Pull request by v-mohithgc**
### Fixed latest CG vulnerabilities 

- [x] run npm audit fix
- [ ] To-do : need to test changes

### CODE REVIEW

**Review by rajnish-byte — APPROVED** [review]
approving as npm audit fix added the req. fixes with some other dependencies. As there was no manual update assuming all are updated to latest version

**Review by mpodriezov — APPROVED** [review]
LGTM

**Pull request closed without merging**
